schema_version = "1.0.0"
id = "savepoints"
version = "1.3.1"
name = "SavePoints"
tagline = "Create save points with previews to restore project versions"
type = "add-on"
website = "https://github.com/unclepomedev/blender_savepoints"
tags = ["System"]

blender_version_min = "4.2.0"

maintainer = "unclepomedev <unclepome.dev@gmail.com>"
license = [
    "SPDX:GPL-3.0-or-later",
]

wheels = [
  "./wheels/Send2Trash-1.8.3-py3-none-any.whl",
]

[description]
text = "A lightweight version control tool for Blender. Create save points with thumbnails and notes, and restore them anytime from the UI."

[permissions]
files = "Create version history and move deleted versions to trash"
