schema_version = "1.0.0"
id = "savepoints"
version = "1.4.1"
name = "SavePoints"
tagline = "Visual version control, easy restore, and automatic timelapse"
type = "add-on"
website = "https://github.com/unclepomedev/blender_savepoints"
tags = ["System", "Pipeline", "Render"]

blender_version_min = "4.2.0"

maintainer = "unclepomedev <unclepome.dev@gmail.com>"
license = [
    "SPDX:GPL-3.0-or-later",
]

wheels = [
  "./wheels/Send2Trash-1.8.3-py3-none-any.whl",
]

[description]
text = "Beyond simple incremental saves, it offers powerful tools to review and utilize your history. Manage versions with visual thumbnails, restore specific objects instantly, and automatically generate timelapses of your progress."

[permissions]
files = "Create version history and move deleted versions to trash"
