schema_version = "1.0.0"
id = "savepoints"
version = "1.0.2"
name = "SavePoints"
tagline = "Create save points with previews to restore project versions"
type = "add-on"

blender_version_min = "4.2.0"

maintainer = "unclepomedev <unclepome.dev@gmail.com>"
license = [
    "SPDX:GPL-3.0-or-later",
]

[description]
text = "A lightweight version control tool for Blender. Create save points with thumbnails and notes, and restore them anytime from the UI."

[permissions]
files = "Create version history next to project file"
